---
- name: Sync hosts ini file into Ansible inventory
  hosts: localhost
  gather_facts: false
  vars:
    inventory_file: "{{ playbook_dir }}/inventory/hosts"
    git_repo_dir: "{{ playbook_dir }}"
    git_commit_msg: "Auto-sync inventory"
    hosts_group: AAP24
    hostname: ansible-automation
    host_ipaddress: 192.168.124.179
    

  tasks:
    - name: Print git repo
      ansible.builtin.debug:
        msg: 
          - "{{ git_repo_dir }}"
          - "{{ inventory_file }}"

    # - name: Write hosts to inventory
    #   lineinfile:
    #     path: "{{ inventory_file }}"
    #     line: "{{ item }}"
    #     create: yes
    #     insertafter: EOF
    #   loop: "{{ new_hosts }}"
    - name: Write hosts to inventory
      community.general.ini_file:
        path: "{{ inventory_file }}"
        section: "{{ hosts_group }}"
        section_has_values:
          - option: "{{ hostname }}"
          - option: ansible_host
            value: "{{ host_ipaddress }}"
        state: present
        allow_no_value: True
        exclusive: True

    - name: Commit inventory changes
      shell: |
        cd {{ git_repo_dir }}
        git add {{ inventory_file }}
        git commit -m "{{ git_commit_msg }}" || echo 'No changes to commit'
        git push
      when: inventory_file is file