---
# File for Ansible UI (Uninstall Microsoft SQL Server) - For Reference as can repeat main.yml in template instead
- name: Actions for MSSQL in a provisioned VM
  hosts: windows
  become: true
  become_method: runas
  become_user: ansible
  gather_facts: true
  tasks:
  - name: Uninstall Microsoft SQL Server 2019
    ansible.builtin.include_role:
      name: mssqlserver
      tasks_from: WindowsUninstall.yml
    # vars:
    #   configtemplate: configUninstall.j2
    #   install_iso_version: SQLServer2019-x64-ENU.iso