---
# tasks file for mssqlserver
- name: Install MSSQL Requirements (Extra Step)
  ansible.builtin.dnf:
    name: ansible-collection-microsoft-sql
    state: present


- name: Install MSSQL Standalone
  ansible.builtin.include_role:
    name: microsoft.sql.server
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_password: "{ mssql_password }"
    mssql_edition: "{ mssql_edition }"
    mssql_enable_sql_agent: true
    mssql_install_fts: true 
    mssql_install_powershell: true
    mssql_tune_for_fua_storage: true