# - name: Install MSSQL using Chocolatey
#   win_chocolatey:
#     name: sql-server-2019
#     state: present
- name: Install MSSQL Server using mssql_install_powershell
  ansible.windows.win_powershell:
    script: |
      Start-Process -FilePath "{{install_dir}}{{setupexecutable}} -ArgumentList "{{argument_list}}" -Wait

- name: Retrieve Microsoft SQL Server Service Status
  ansible.windows.win_service:
    name: 'MSSQLSERVER'
  register: service_info

- name: Print the Service Information Status
  ansible.builtin.debug:
    var: service_info