---
- name: Create temp folder on target
  ansible.windows.win_file:
    path: 'C:\temp'
    state: directory

# src: 'files/configpatch.j2'
- name: Copy the configuration.ini file to target
  ansible.builtin.template:
    src: 'files/{{ configtemplate }}'
    dest: 'C:\temp\Configuration.ini'

- name: Check Version
  ansible.builtin.include_tasks:
    file: MSSQLCheck.yml

- name: Patch Standalone instance
  ansible.windows.win_powershell:
    script: '{{patch_dir}}{{patch_name}}.exe /ConfigurationFile=C:\temp\Configuration.ini /IAcceptSQLServerLicenseTerms=True'

# - name: Check Version
#   ansible.builtin.include_tasks:
#     file: MSSQLCheck.yml

# - name: Patch Standalone instance
#   ansible.windows.win_powershell:
#     script: '{{patch_dir}}{{patch_name}}.exe /quiet /IAcceptSQLServerLicenseTerms /Action=Patch -Wait'

- name: Cleanup temp directory
  ansible.windows.win_file:
    path: 'C:\temp'
    state: absent

- name: Check Version
  ansible.builtin.include_tasks:
    file: MSSQLCheck.yml

- name: Get Status from Logs
  ansible.builtin.win_powershell:
    script: | 
      Get-Content 'C:\Program Files\Microsoft SQL Server\{{folder_no}}\Setup Bootstrap\Log\Summary.txt' | Select -First 7
  vars: 
    folder_no: 150
  register: file_content

- name: Server Name and Version from (SSMS)
  ansible.builtin.debug:
    var: file_content