---
- name: Create temp folder on target
  ansible.windows.win_file:
    path: 'C:\temp'
    state: directory

# - name: Copy ISO to target
#   ansible.windows.win_copy:
#     src: '/home/SQLServer2019-x64-ENU.iso'
#     dest: 'C:\temp\'

#src: 'files/config2019uninstall.j2'
- name: Copy the configuration.ini file to target
  ansible.builtin.template:
    src: 'files/{{ configtemplate }}'
    dest: 'C:\temp\Configuration.ini'

#image_path: 'C:\SQLServer2019-x64-ENU.iso'
- name: Mount ISO
  community.windows.win_disk_image:
    image_path: 'C:\{{ install_iso_version }}'
    state: present
  register: mssql_iso_image

- name: Debug MSSQL ISO image
  ansible.builtin.debug:
    var: mssql_iso_image.mount_paths[0]

# - name: Install Standalone instance
#   ansible.windows.win_command:
#     cmd: '{{ mssql_iso_image.mount_paths[0] }}setup.exe /ConfigurationFile=C:\temp\Configuration.ini'

- name: Microsoft SQL Server Service Info Before
  ansible.windows.win_service:
    name: 'MSSQLSERVER'
  register: service_info

- name: Print the Service Information Before
  ansible.builtin.debug:
    var: service_info

- name: Install/Patch Standalone instance
  ansible.windows.win_powershell:
    script: '{{ mssql_iso_image.mount_paths[0]}}setup.exe /ConfigurationFile=C:\temp\Configuration.ini'
      
- name: Microsoft SQL Server Service Info After
  ansible.windows.win_service:
    name: 'MSSQLSERVER'
  register: service_info

- name: Print the Service Information After
  ansible.builtin.debug:
    var: service_info

#image_path: 'C:\SQLServer2019-x64-ENU.iso'
- name: Unmount ISO
  community.windows.win_disk_image:
    image_path: 'C:\{{ install_iso_version }}'
    state: absent

- name: Cleanup temp directory
  ansible.windows.win_file:
    path: 'C:\temp'
    state: absent